env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts"
   - "QUBELL_TENANT=https://express.qubell.com"
   - "PROVIDER_TYPE=aws-ec2"
   - "PROVIDER_REGION=us-east-1"
   - secure: "fUx95ebjptJ2iEs9hd+aPpHX+yRJYZTtCUrx2TXXnHFnL4T1s8X3lbYzX9l76iv5GI60eggV3FXR63KOcpiWd8CwXEhDTIpen+eA8lor9Tw/0skQn1sxwy4wigaN4flXHvSEI6h4WDfRPD5espC9J39fg82jQ7SLzV8Y+DzR5Bg="
   - secure: "FC5PSGqBwIiFbbNfSA8p/wG71akxK5UF77BW+A3tYuUxhIAJtz18d1tSqvC7CHx3PQefRHxrW/g/yt9DGPCxVUl46Q6EybqbaeJKwrlRaA7hQWoRQ3qh76ZLrzQ4bojk7ZEHXOTN0WOXSa8751chlmUymX8d2KaK1m3BAjcjBpI="
   - secure: "MBxm/L/I1ARll0CvQ7rUeMwuHMKJIQVt3Ll4d7Fsd+ICSj+dWyzuQlt39gDIUcMw7L38G1dT//tuohoQf7TnoaL9/V+IVDuqqo+V/0mNCxDD/87B/3Uds2zn43+8KjOmE5OIvaDjNRhrT/cQCrfD4/XNnA4Q4rRsWaaonQSp+J4="
   - secure: "Q+l6oh240mbvWWQebjB6ryYvXmgqfG2O9D/eUIl3+BzzFAb3/hOunPwEXVg1ubbfP0sU/Lb9AsIyNhItBfTKEigzc9xTx2oGHlSXeHnuJmmOio51LekFhO+lpE+hoaXRvUNa/SRT2c2hstdZSiF57y+mh7X0C0sbzf8gcMfG7RE="
   - secure: "WpEO4zCMyFrnpAnGO+F956vWyflZNVT7v3D+beRQ/JofxJJ+gv50qwcifyoEqODX7UBaVke0Vg9nkDuAVKZd9ZEdwwNSLxg4bRQGZ+Q6VFtn7j+BFp7amior1n1dnO75EvFv2FsoGcLcPUm0OnUmaLaJS9uV6h21M2t+nfJB5ig="

language: python
python:
  - "2.7"

install: "pip install -r test/requirements.txt"

before_script:
   - gem install travis-artifacts --no-ri --no-rdoc
   - git submodule update --init --recursive
   - ./build.sh dev
   - ./upload.sh dev
   - REPO_NAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d/ -f2); sed -i 's/${REPO_NAME}-cookbooks-stable/${REPO_NAME}-cookbooks-dev/g' ${REPO_NAME}.yml

script: python test/main.py

after_success:
  - ./build.sh stable
  - ./upload.sh stable
