env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: DCHKNChWO21wlslmQCy58jhLyKXsjnBRWa3p2rqqiFt/p58Ne6VgT7tyKQ2omT06+zNXYpyLbeA7GWWc9bOKLcmS5lYN4EZp3kDwi3KfrfoT5WV76ku/MaPM3pXfqzRzOrtfC/2ql3Th27UbhPuENHzKz3vez2hI2IrcFoNSwqw=
  - secure: YjVUSvvKiwuoenz8m+8gmQv0u9jvTAu2H89qwmyLDZNnY86Ef2/9wpftlAS31FNFEg+TW2EHPCQid7myOZ7b8bBGdViLJffM0XRr3cZSlyLATlCU/A8aR4aAddcUqUbW09yJx17lwBDVe01xWlnvO/d0Yhm4zHSicOHr/UaXTeg=
  - secure: aNHR0UeTfZQh7yV4TN918c0LJfyYmZxoiopaGAPCoNeK/eutJ4C0YXMZuK/vqC5elXMVxuA2t+1t5vubNaKU/We8WxpZ/jYhWq74wjLse0n0EOcNDXZVJIAUhY6yYxxgl5T3leDGVfM1N8anFa9iWWyK+ngoDSK3iEc+asR/t8s=
  - secure: Urp0BRrNFVbB1ZKXLJqYMeSxu8wKfXyWmeb/Ve89fRXY1B546FQsnIc32y8EOJ1MgfqYfqSROvKtpKBgk5zDifA5h+agNJroMU8fSmCQaD+tgF2rbyr1x4A1F6iCnLGe5csKm2mp/gDYzx8WjjjOXbMpuzOjU/7wsBIjhmNMGAM=
  - secure: IK25ScBt6/ZQ3YUNtfn/Ph38Sbg3V6Eu4oXSBSV+ZIv2V97bRZAXyRUHxFAIzduQGBTRb4bvwKxcCqmvzqsSUZ5v0KRUKXc2JAEFLJb+HLg7nI5luKoij6UCGw6sZLlD4ptYPNKlRcpd0Pqvoul0Oec42NmQ3e4iY5od1sj7al0=
  - secure: Z255aBXHCkReVejLHbYtUaNsT0PzHz4oci6W5e2zNNCxJ03U7goh5vekLK/2MRhY5Az6wd3Ar+hzYpo88RPSNtckLtflZ2qufZ6i8eYpFDfighIOe1cCmcgAKPKh9yv9Ej52XjNykuzcvaYVkcPrfqzGAyP4pH6HqTdDW1f6Jcc=
  - secure: XRQ4CM8FepiDhww4zpuTwS3g5zOwk9yJaMvtPISovFoEGQkg1LsPOVJDp46G38BOVRRoATKiw4QKM5EnrlmBvE24gR2JPbe9GEgEdDUZsQGWGwiR7vkqKztdiEK1lgZijLI6xz5s5Uo7lwYth+0BcrtTASWBJfsLwZsQyEXw1HE=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
