kit:
  name: "MySQL 5 (Dev)"
  link: https://github.com/qubell-bazaar/component-mysql-dev 
  applications:
    - name: "Database"
      manifest: https://raw.github.com/qubell-bazaar/component-mysql-dev/1.1-35p/component-mysql-dev.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 3306 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
